import type { AgentSnapshot } from "../../shared/contracts.js";

export const EMPTY_AGENT_SNAPSHOT: AgentSnapshot = {
  projectPath: null,
  projectName: null,
  sessionId: null,
  sessionFile: null,
  sessionTitle: null,
  sessions: [],
  timeline: [],
  timelineHasMore: false,
  models: [],
  selectedModel: null,
  thinkingLevel: "off",
  thinkingLevels: ["off"],
  isStreaming: false,
  workingStartedAt: null,
  pendingCount: 0,
  error: null,
  canContinue: false,
  taskPlan: null,
  explorers: [],
  extensionUi: null,
  history: { available: false, canUndo: false, canRedo: false, isBusy: false, message: null },
  validation: {
    supported: false,
    isSelfProject: false,
    status: "idle",
    runId: null,
    activeStep: null,
    steps: [],
    sourceRevision: null,
    originToolCallId: null,
    startedAt: null,
    verifiedAt: null,
    message: null,
  },
  review: {
    available: false,
    baseCommit: null,
    headCommit: null,
    files: [],
    patch: "",
    truncated: false,
    message: null,
  },
  candidate: {
    status: "idle",
    candidateId: null,
    candidatePath: null,
    preparedAt: null,
    message: null,
    history: [],
  },
  context: {
    tokens: null,
    contextWindow: null,
    percent: null,
    canCompact: false,
    isCompacting: false,
    isEstimated: false,
    compactionMethod: null,
    compaction: { status: "idle" },
  },
  policy: { contextFiles: [], workflow: "manual-review", gitCommits: "required-after-verification" },
};
